### ISSUE TITLE
Key Functionality

### ISSUE THREAD

**Issue by KodyFintak** [Kodyfint/3Dvs2D_vr#21]
Making the key collectable by player and when a player dies, player drops all keys.
Show on UI that keys have been collected.
When all keys collected, 2D player (DM) loses and no longer works.
Players all get teleported to an arena (or just duke it out in map)
Last player left wins

**Comment by AllenGNg** [comment]
Having more keys may also "power up" the holder, such as more health or damage.

**Comment by AllenGNg** [comment]
Almost working, Sometimes when a key is picked up, it counts as 3 instead of 1. This is the same whether it is spawned by the 2D player or dropped when a player is killed. Also, I can't seemed to spawn keys in different spots after a player is killed and is holding more than 1 key.

**Comment by AllenGNg** [comment]
Keys now correctly count as 1 key when they are picked up, and when a player dies, now also correctly drops the right amount.
