### ISSUE TITLE
Create full 2D player 

### ISSUE THREAD

**Issue by KodyFintak** [Kodyfint/3Dvs2D_vr#6]
Create a full 2D player that contains the following: 
- a moveable camera 
- move spawning UI over to the player, except be able to spawn enemy at point clicked
- be able to make paths for a enemy to follow
- be able to spawn a "trap" and the clicked location ("trap will be made next sprint, just put a empty game object") 
- be able to spawn 4 keys for player to collect
- warp player either randomly or to a certain point
- send messages to all player 
- Have cool downs for spawns and what not 
- Modify players (speed boosts/extra damage)

**Comment by Siushi** [comment]
In 2D branch

**Comment by Siushi** [comment]
d590762d2b07e644abae526373df88b4f66080fb Cleaner 2D
